name: RealAdminTools
main: fr.crafter.tickleman.RealAdminTools.RealAdminToolsPlugin
version: 0.04
website: http://plugins.crafter.fr/tickleman/RealAdminTools/
authors:
  - tickleman
commands:
  config:
    description: change configuration options from server.properties
    usage: /<command> <option> <value>
  entities:
    description: entities summary
    usage: /<command> [detail]
