name: RealAdminTools
main: fr.crafter.tickleman.realadmintools.RealAdminToolsPlugin
version: 0.20
website: http://plugins.crafter.fr/tickleman/RealAdminTools/
author: tickleman
depend: [RealPlugin]
commands:
  config:
    description: change configuration options from server.properties
    usage: /<command> [<option> [<value>]]
  entities:
    description: entities summary
    usage: /<command> [detail]
  ops:
    description: display operators list
    usage: /<command>
  tasks:
    description: display tasks list
    usage: /<command>
